#
#  Makefile for the kernel Sensor device drivers.
#

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_ALPS)		+= alps-input.o
obj-$(CONFIG_SENSORS_HSCDTD006A) 			+= hscdtd006a_i2c.o
obj-$(CONFIG_SENSORS_HSCDTD008A)			+= hscdtd008a_i2c.o
obj-$(CONFIG_SENSORS_BMA222)		+= bma222.o
obj-$(CONFIG_SENSORS_BMA222E)		+= bma222e.o
obj-$(CONFIG_USE_BMA_INITLIB)	+= bmainit.o
obj-$(CONFIG_SENSORS_K2DH)	+= k3dh.o
obj-$(CONFIG_PROXIMITY_SENSOR)	+= gp2a.o
obj-$(CONFIG_SENSORS_BMA2X2)	+= bma2x2_driver.o bst_sensor_common.o    
obj-$(CONFIG_SENSORS_BMM050)	+= bmm050_driver.o bmm050.o
obj-$(CONFIG_SENSORS_PX3215)	+= px3215.o
obj-$(CONFIG_SENSORS_GYRO_K3G)	+= k3g.o     
obj-$(CONFIG_SENSORS_GP2A030)	+= gp2ap030.o