#!/bin/bash
#echo "rebooting recovery"
#adb shell "su -c 'reboot recovery'"
echo "Waiting for device"
adb wait-for-device
mkdir tmp 
cp kernel-$(date +%Y%m%d)-3.4.82-UNOFFICIAL-delos3geur.zip tmp/
cd tmp
unzip *.zip
echo "PUSHING BOOT.IMG"
adb push boot.img /sdcard/boot.img
echo "Flashing "
adb shell "su -c 'dd if=/sdcard/boot.img of=/dev/block/mmcblk0p8'"
adb shell rm /sdcard/boot.img
adb shell "su -c 'reboot'"
cd ..
rm -rf tmp
clear
